FROM node:14.18.1-alpine

WORKDIR /usr/src/log

COPY package.json .
COPY package-lock.json .

RUN adduser -S appuser
RUN npm install --production

COPY log.js .

USER appuser

CMD ["node", "log.js"]