apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: hash
          persistentVolumeClaim:
            claimName: log-pv-claim
      containers:
        - name: log-output-hash
          image: mixu78/log-output-hash:1.11
          volumeMounts:
            - name: hash
              mountPath: /usr/src/app/files

        - name: log-output-log
          image: mixu78/log-output-log:1.11
          volumeMounts:
            - name: hash
              mountPath: /usr/src/app/files