apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: hash
          emptyDir: {}
      containers:
        - name: log-output-hash
          image: mixu78/log-output-hash:1.10
          volumeMounts:
            - name: hash
              mountPath: /usr/src/log/files

        - name: log-output-log
          image: mixu78/log-output-log:1.10
          volumeMounts:
            - name: hash
              mountPath: /usr/src/log/files