apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: mixu78/ping-pong:3.09
          env:
            - name: POSTGRES_HOST
              value: postgres-svc
            - name: POSTGRES_DB
              value: ping-pong
            - name: POSTGRES_USER
              value: kubernetes
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: "20m"
              memory: "400Mi"