apiVersion: v1
kind: Service
metadata:
  name: ping-pong
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - name: ping-pong
      port: 2223
      protocol: TCP
      targetPort: 3001