apiVersion: ENC[AES256_GCM,data:ccE=,iv:MLPTQ54PQt6KWMJvIaNAhfcp0QZPe708mQi8IPNOkVY=,tag:hdUxInZf7ft+2Z8chNtTrQ==,type:str]
kind: ENC[AES256_GCM,data:gTyJzNSm,iv:mptoJkMG/Uj2BS0auikVLJyyR0Gbna68XDkhhQyFh1c=,tag:ZBcoNIYrBwOdM368go3B+A==,type:str]
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:aBHqv3vrrIo=,iv:qPlASK9urXL+VWxJHUpRnNuqEQXsDikDC4gncWBnVsA=,tag:ealnLVIB3HY6xd7O7K7uYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c8t6snq0lza6nljl9y8wet6g4et4cjrrvfkg5n575yu9tfdnhftsmsfly5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RDdZR01OampuVXE5eE1p
            MStiYlVGZk51a0ZPUmxnR1F5dm1LekRzbHdzCkhyRWdubXNEVnhobnM5M0RTMGM0
            cTRBOFVkUXJxTmVjSHJmdUV4Z0pyVjAKLS0tIHY5K1o2aGNBbnkzZ2Y3R3pXZE5K
            L3FLVXlmS2o2Y0VKNjFvVFJKQ2RLUW8KecgsUFLJQt4Ax2WQKs7+EtFy9YMJodma
            6Qwq/NKamb/wOOq4KNZ5cQoBOJHMyIXGPxjFUnD4IfHijNX9zgwO3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-20T19:37:43Z"
    mac: ENC[AES256_GCM,data:FDJpehexa8YIXcpulFb1Gnt0gs4xCft9SFrYtfIdWQMNZgTrk2ppGr4MslhVuhWW2pErtV0nI6202uk268j4zF0sw8P2nyQtCkVAX0s/hE3NWM0TwgrPD/t5JY7ae2tH9tMe5hWFkxBbWlo1vr9Nb5c0pt7zeL1ofXq/5KEdr8E=,iv:rsilWVpYySjmqRfjvOTlG8uTK55BxCPCE825C+sr+lE=,tag:IPWBXVLjJZ51bpkoIwk7aw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
